version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: worktrack-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: worktrack
      POSTGRES_PASSWORD: worktrack_secret
      POSTGRES_DB: worktrack
    ports:
      - '5432:5432'
    volumes:
      - worktrack_pg_data:/var/lib/postgresql/data

volumes:
  worktrack_pg_data:
